{{ if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app }}
      app.kubernetes.io/version: {{ .Values.version }}
  {{- if .Values.networkPolicy.policyTypes }}
  policyTypes:
  {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
  {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
  {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{ end }}
