name: Main

on:
  push:
    branches:
      - main

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    name: Docker
